baseURL = "http://isaacgounton.github.io/"
languageCode = "en-us"
title = "Personal Site"
publishDir = "isaacgounton.github.io"

[permalinks]
blog = "/:filename/"

[params]
dateFormat = "Jan 2, 2006"
author = "Isaac Gounton"
motto = "ReactJs, NodeJs, Python and cheap poetry"

[taxonomies]
tag = "tags"
